//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansTesComs.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentaireExterne
    {
        public CommentaireExterne()
        {
            this.CommentairesExterneContents = new HashSet<CommentairesExterneContent>();
            this.Notes = new HashSet<Note>();
            this.Commentaires = new HashSet<Commentaire>();
        }
    
        public int Id { get; set; }
        public int PosterUserId { get; set; }
        public System.DateTime DatePost { get; set; }
        public string Titre { get; set; }
        public string Lien { get; set; }
        public string Publication { get; set; }
        public bool IsValide { get; set; }
        public string lang { get; set; }
        public string Categories { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<CommentairesExterneContent> CommentairesExterneContents { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Commentaire> Commentaires { get; set; }
    }
}
