//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansTesComs.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CommentaireExternes = new HashSet<CommentaireExterne>();
            this.Notes = new HashSet<Note>();
            this.Commentaires = new HashSet<Commentaire>();
            this.Roles = new HashSet<Role>();
            this.NotesCommentaires = new HashSet<NotesCommentaire>();
        }
    
        public int Id { get; set; }
        public string Mail { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> Anniversaire { get; set; }
        public System.DateTime InscriptionDate { get; set; }
        public string Pseudo { get; set; }
    
        public virtual ICollection<CommentaireExterne> CommentaireExternes { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Commentaire> Commentaires { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<NotesCommentaire> NotesCommentaires { get; set; }
    }
}
