//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansTesComs.WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentairesExterneContent
    {
        public int Id { get; set; }
        public string Pseudo { get; set; }
        public string Commentaire { get; set; }
        public int Niveau { get; set; }
        public int CommentaireExterneID { get; set; }
    
        public virtual CommentaireExterne CommentaireExterne { get; set; }
    }
}
