//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansTesComs.WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CommentaireExternes = new HashSet<CommentaireExterne>();
        }
    
        public int id { get; set; }
        public string mail { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> Anniversaire { get; set; }
        public Nullable<System.DateTime> InscriptionDate { get; set; }
        public bool isAdmin { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<CommentaireExterne> CommentaireExternes { get; set; }
    }
}
